### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by kojix2**
Make README look friendly.

### CODE REVIEW

**Comment by kou** [comment]
I like the current format.

**Comment by kojix2** [comment]
Why do you prefer the current format?

I guess that the product is not mature enough and you want to focus on improving the product before updating readme. 
Right?

**Comment by kou** [comment]
This is a README file. So using "README" as the biggest heading isn't strange for me. `man` also has `NAME` section. So using "Name" section isn't strange for me too.
So I don't know what/how this change improves the current situation.

If someone maintains documentation, he/she will decide what format we use. But the current maintainer of documentation is me. So I need to decide it.

**Comment by kojix2** [comment]
This answer is very interesting to me.

It sounds like you are processing information as text, like a parser.
But I feel like I am processing information as an image..

In Github, README is a landing web page. 
The people who visit Red OpenCV's Github page want to run OpenCV with Ruby.
And the first thing they want to do is to check if they come to the right page. 
Therefore, I think the letters of "Red OpenCV" should be the largest to help people get information.

But my idea may be too dependent on the current Github-centric ecosystem.

Of course, you are the maintainer and have the right to choose how do it.
You manage so many repositories, you need to do the right thing.

**Comment by kou** [comment]
This is too trivial for me.
If we need to discuss this, I just merge this and want to stop this discussion. Because this is too trivial for me.

**Comment by kojix2** [comment]
Hmm.
My personal guess is that you may have a lot of work to do and need rest and someone to help you. 
Thanks anyway.

**Pull request merged**
